name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-12
    name: 3.1
    steps:
    - uses: actions/checkout@v3
    - name: OpenBSD Test
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        prepare: |
          pkg_add ruby31-pledge ruby31-unicorn nginx
          gem31 install -N mail roda minitest-global_expectations
          groupadd _unicorn
        run: |
          rake31 test_ci
